import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CardActionsContextProvider } from "../components/context/card-actions-context";
import { Toaster } from "sonner";
import { PaginationProvider } from "@/components/context/pagination-context";
import { AuthProvider } from "@/components/context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-screen w-screen m-auto px-[10%] py-[2%]">
          <AuthProvider>
            <PaginationProvider>
              <CardActionsContextProvider>
                {children}
              </CardActionsContextProvider>
            </PaginationProvider>
          </AuthProvider>
        </main>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
