services:
  db:
    image: postgres:alpine
    container_name: db-solp-pet
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    